[platformio]
default_envs = opta

[env:opta]
platform = ststm32
board = opta
framework = arduino
monitor_speed = 9600
upload_protocol = dfu
lib_ldf_mode = deep+
build_flags =
  -I"$PROJECT_LIBDEPS_DIR/$PIOENV/Arduino_SerialUpdater/src"
  -I"$PROJECT_LIBDEPS_DIR/$PIOENV/Arduino_DebugUtils/src"
  -DOPTA_PROFILE_PIANO1
lib_deps =
  knolleary/PubSubClient@^2.8
  https://github.com/arduino-libraries/Arduino_Opta_Blueprint.git
  https://github.com/arduino-libraries/Arduino_Portenta_OTA.git
  arduino-libraries/Arduino_SerialUpdater
  arduino-libraries/Arduino_DebugUtils

[env:opta_piano2]
platform = ststm32
board = opta
framework = arduino
monitor_speed = 9600
upload_protocol = dfu
lib_ldf_mode = deep+
build_flags =
  -I"$PROJECT_LIBDEPS_DIR/$PIOENV/Arduino_SerialUpdater/src"
  -I"$PROJECT_LIBDEPS_DIR/$PIOENV/Arduino_DebugUtils/src"
  -DOPTA_PROFILE_PIANO2
lib_deps =
  knolleary/PubSubClient@^2.8
  https://github.com/arduino-libraries/Arduino_Opta_Blueprint.git
  https://github.com/arduino-libraries/Arduino_Portenta_OTA.git
  arduino-libraries/Arduino_SerialUpdater
  arduino-libraries/Arduino_DebugUtils
